### PR TITLE
Fix Aerobee atmosphere curve and reimplement Large landing gear

### PR DESCRIPTION
**Pull request by notquitehalf**
Using @EmbersArc tutorial, the large landing gear from a few versions back has been updated to use the new landing leg system. Also corrected the atmosphere curves for the Aerobee engines

### CODE REVIEW

**Comment by EmbersArc** [comment]
"Large landing legs" as in Ven's SpaceX-like ones?

**Comment by notquitehalf** [comment]
Yeah, those are the ones. Just did some more testing, and I've realised that they've broken a little since I last worked on them a few weeks back

**Comment by notquitehalf** [comment]
Might be better to close this for now. I'll post back when I've fixed them up a little more

**Comment by EmbersArc** [comment]
Yes I've also found my Falcon legs to perform worse. They skitter around a lot. I've found a slightly simpler setup than the one in the tutorial. But the issue seems to persist.

**Comment by notquitehalf** [comment]
Yeah, I was having that trouble until I tried using your tutorial funnily enough. They are stable now, but a new update seems to have changed some stuff. I made sure that the animation for the leg avoids the Z direction getting flipped (and thus making the whole leg turn 180° when stowed), but that seems to have messed up in the newest version. Regardless, I'll try to iron this stuff out.

Thanks for that tutorial though, it really helped solve 90% of the problems I had getting these to work!

**Pull request merged**
